PRAGMA foreign_keys=ON;

CREATE TABLE "User" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "email" TEXT NOT NULL UNIQUE,
    "password" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Keyword" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "value" TEXT NOT NULL UNIQUE,
    "active" BOOLEAN NOT NULL DEFAULT TRUE,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Setting" (
    "id" INTEGER PRIMARY KEY,
    "nextKeywordIndex" INTEGER NOT NULL DEFAULT 0,
    "nextCodeCounter" BIGINT NOT NULL DEFAULT 0,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Link" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "slug" TEXT NOT NULL UNIQUE,
    "keyword" TEXT NOT NULL,
    "code" TEXT NOT NULL,
    "longUrl" TEXT NOT NULL,
    "redirectType" INTEGER NOT NULL DEFAULT 302,
    "expiresAt" DATETIME,
    "enabled" BOOLEAN NOT NULL DEFAULT TRUE,
    "clicks" INTEGER NOT NULL DEFAULT 0,
    "userId" INTEGER NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE
);

CREATE INDEX "Link_userId_idx" ON "Link"("userId");

CREATE TABLE "Click" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT,
    "linkId" INTEGER NOT NULL,
    "ipHash" TEXT NOT NULL,
    "referrer" TEXT,
    "userAgent" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("linkId") REFERENCES "Link"("id") ON DELETE CASCADE
);

CREATE INDEX "Click_linkId_idx" ON "Click"("linkId");
